site:
    # Site name
    title: My Node Site
    title_sub_line: something of meaning.
    # Background color for title bar
    title_bar_rgb: 44f
    # Background color for footer bar
    footer_bar_rgb: 44f
    footer: NomadNetwork Site

pages:
    # Name that appears in menu
    Home:
        file: /<home>/.nomadnetwork/storage/pages/home.mu
        type: mu
    Message Board:
        file: /<home>/.nomadnetwork/storage/pages/message_board.mu
        type: python
    Status:
        file: /<home>/.nomadnetwork/storage/pages/status.mu
        type: python
    About:
        file: /<home>/.nomadnetwork/storage/pages/about.mu
        type: mu
    Games:
        file: /<home>/.nomadnetwork/storage/pages/gamesmenu.mu
        type: python
